name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    env:
      MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      # List all files in the current directory for comparison before and after actions/checkout@v2.
      - run: ls -l
      - uses: actions/checkout@v2
      - run: ls -l
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 #5.1.0
        # uses: aws-actions/configure-aws-credentials@5.1.0 # test
