name: Upload file artifact

on:
    workflow_dispatch:

jobs:
    upload-file:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Generate file
              run: echo "Generated at $(date)" > sample.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sample-git.txt
                path: sample.txt
                retention-days: 30
    download-file:
        needs: upload-file
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Before downloaded file
              run: |
                ls -l 
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: sample-git.txt
                path: .
            - name: Verify downloaded file
              run: |
                ls -l
                cat sample.txt